config/routes.rb
Rails.application.routes.draw do
  resources :rooms do
    resources :messages
  end

  root 'pages#home'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get 'users', to: 'devise/session#new'
  end
  # Defines the root path route ("/")
  # root "articles#index"

  get 'user/:id', to: 'users#show', as: 'User'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  after_create_commit { broadcast_append_to self.room }
end

app/models/room.rb
class Room < ApplicationRecord
    validates_uniqueness_of :name
    scope :public_rooms, ->{ where(is_private: false) }
    after_create_commit { broadcast_append_to 'rooms' }
    has_many :messages
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  scope :all_except, -> (user) { where.not(id: user) }
  after_create_commit { broadcast_append_to "users" }
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @current_user = current_user
    @message = @current_user.messages.create(body: msg_params[:body], room_id: params[:room_id])
  end
  private

  def msg_params
    params.require(:message).permit(:body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def index
  @room = Room.new

  @rooms = Room.public_rooms

  @users = User.all_except(current_user)
  end

  def show
    @single_room= Room.find(params[:id])
    @rooms = Room.public_rooms
    @users = User.all_except(@current_user)
    @room = Room.new
    @message = Message.new
    @messages = @single_room.messages
    render "index"
  end

  def create
   @room = Room.create(name: params["room"]["name"])
  end

end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
    class Responder < ActionController::Responder
        def to_turbo_stream
            controller.render(options.merge(format: :http))
        rescue ActionView::MissingTemplate => e
            if get?
                raise e
            elsif has_errors? && default_action
                render rendering_options.merge(format: :http,status: :unprocessable_entity)
            else
                redirect_to navigation_location
            end
        end
    end

    self.responder = Responder
    respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">

      Let's Chat
    </a>
  </div>
</nav>

app/views/layouts/_new_message_form.html.erb
<div class="form-group msg-form">
  <%= form_with(model: [@single_room, @message], remote: true, class:'d-flex' ) do |f| %>
    <%= f.text_field :body, id: 'chat-text', class: "form-control msg-content", autocomplete: 'off' %>
    <%= f.submit data: { disable_with: false }, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/_new_room_form.html.erb
<%= form_with(model: @room, remote: true, class: "d-flex" ) do |f| %>
  <%= f.text_field :name, class: "form-control", autocomplete: 'off' %>
  <%= f.submit data: { disable_with: false } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Turbochat</title>
    <%= favicon_link_tag asset_path("index.jpeg")%>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <style>
    <%= "msg-#{current_user&.id}"%>{
    background-color:#007bff !important;
    padding: 10px;
    }
    <%= "cont-#{current_user&.id}"%>{
      display: flex;
      justify-content: flex-end;
    }
    </style>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "layouts/navbar"%>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="cont- <%=message.user.id%>">
  <div class="message-box msg-<%= message.user.id%>">
    <% unless message.room.is_private %>
      <h6> <%= message.user.email%> </h6>
    <% end %>
    <%= message.body %>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p> 

<% if current_user%>
<%= button_to "logout",destroy_user_session_path, method: :delete %>
<%= link_to "Chats",rooms_path%>
<% else %>
<%= link_to "login",new_user_session_path%>
<%= link_to "Sign Up",new_user_registration_path%>
<% end %>

app/views/rooms/_room.html.erb
<div>
    <%= link_to room.name, room %>
</div>

app/views/rooms/index.html.erb
<div id="chatroom_container" class="row bg-dark text-light">
    <div id="side_panel" class="col-md-4 col-sm-4">
        <h5><%= current_user.email%></h5>

        <h4>User</h4>
        <%= turbo_stream_from "users"%>
        <div id="users">
            <%= render @users %>
        </div>
        <h4>Rooms</h4>
        <%= render 'layouts/new_room_form' %>
        <%= turbo_stream_from "rooms"%>
        <div id="rooms">
            <%= render @rooms %>

        </div>
    </div>
        <div id="room_container" class="col-md-8 col-sm-8 bg-dark text-light">
            <% if @single_room %>
            <div id="single_room">
                <h4 class="text-center"> <%= @user&.email||@single_room.name %> </h4>

                <%= turbo_stream_from @single_room%>
                <div id="message">
                    <%= render @messages %>
                    <%= render 'layouts/new_message_form' %>
                </div>

            </div>
            <% end %>
        </div>

</div>

app/views/users/_user.html.erb
<div>
    <%= link_to user.email,  User%>

</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>